name: Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flutter_test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Proyecto_Moviles_II_Huallpa-Escobar-Anahua-Zevallos-Salinas-Soto-main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'  # ✅ Compatible con Dart ^3.7.2
      - name: Analyze

        run: flutter analyze

 

      - name: Run tests

        run: flutter test
