name: Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Proyecto_Moviles_II_Huallpa-Escobar-Anahua-Zevallos-Salinas-Soto

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project (allow warnings)
        run: flutter analyze || true

      - name: Run Unit Tests
        run: flutter test
