name: Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flutter_test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'  # Cambia si usas otra versión

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./Proyecto_Moviles_II_Huallpa-Escobar-Anahua-Zevallos-Salinas-Soto-main

      - name: Analyze project
        run: flutter analyze
        working-directory: ./Proyecto_Moviles_II_Huallpa-Escobar-Anahua-Zevallos-Salinas-Soto-main

      - name: Run tests
        run: flutter test
        working-directory: ./Proyecto_Moviles_II_Huallpa-Escobar-Anahua-Zevallos-Salinas-Soto-main
