name: Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flutter_test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'  # o '3.32.5' si tu pubspec usa Dart >=3.7.2

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test
